Repository BEMINE-UMC/Server, pull requests merged in 2025-02, with the labels that each got.

#157 [refactor] 이미지 업로드 api ignore
  src/index.js
Labels: :memo: docs, :recycle: refactor

#159 [feature] 연혁수정 API
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/errors/user.error.js
  src/index.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :sparkles: feature

#163 feat/#162-verify-data
  src/controllers/auth.controller.js
  src/dtos/auth.dto.js
  src/errors/auth.error.js
  src/index.js
  src/repositories/auth.repository.js
  src/services/auth.service.js
Labels: :sparkles: feature

#166 docs/#162-add-swagger
  src/controllers/auth.controller.js
Labels: :memo: docs

#167 [refactor] 연혁 조회 수정
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/repositories/user.repository.js
Labels: :recycle: refactor

#169 ✨ [Feat] 연혁 생성
  prisma/schema.prisma
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/index.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :sparkles: feature, :recycle: refactor

#172 refactor: (템플릿 인증뱃지를 위한) 설문 완료 수 전송
  prisma/schema.prisma
  src/controllers/template.controller.js
  src/dtos/template.dto.js
  src/repositories/template.repository.js
Labels: :recycle: refactor

#175 :sparkles: [Feat] 마이페이지 사용자 정보 조회
  prisma/schema.prisma
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/index.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :sparkles: feature, :recycle: refactor

#177 ♻️ [Refactor] 연혁 생성
  prisma/schema.prisma
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :recycle: refactor

#179 :recycle: [Refactor] N+1 최적화 완료
  src/dtos/user.dto.js
  src/repositories/post.repository.js
  src/repositories/user.repository.js
  src/services/post.service.js
  src/services/user.service.js
Labels: :recycle: refactor

#181 연혁수정/자기소개 수정
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :recycle: refactor

#184 feat: create survey
  src/controllers/template.controller.js
  src/dtos/template.dto.js
  src/index.js
  src/repositories/template.repository.js
  src/services/template.service.js
Labels: :sparkles: feature

#187 [Refactor] 템플릿 목록 조회 api 수정 (뱃지)
  src/dtos/template.dto.js
  src/repositories/template.repository.js
Labels: :recycle: refactor

#188 main -> develop
  src/controllers/template.controller.js
  src/dtos/template.dto.js
  src/index.js
  src/repositories/template.repository.js
  src/services/template.service.js
Labels: :memo: docs, :sparkles: feature, :recycle: refactor

#195 :recycle: [refactor] 템플릿 생성 status 추가
  src/dtos/template.dto.js
  src/repositories/template.repository.js
Labels: :recycle: refactor

#198 feat/#197-닉네임 중복 검사 API
  src/controllers/auth.controller.js
  src/dtos/auth.dto.js
  src/errors/auth.error.js
  src/index.js
  src/repositories/auth.repository.js
  src/services/auth.service.js
Labels: :sparkles: feature

#205 [Refactor] 게시물, 템플릿 별 총 좋아요 개수 집계 (메인페이지)
  src/controllers/post.controller.js
  src/controllers/template.controller.js
  src/dtos/post.dto.js
  src/dtos/template.dto.js
  src/repositories/post.repository.js
  src/repositories/template.repository.js
Labels: :memo: docs, :recycle: refactor

#208 [refactor] 게시글 작성 수정
  src/services/post.service.js
Labels: :recycle: refactor

#213 refactor: 작성 post에 사용자 이름 추가
  src/dtos/post.dto.js
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: :recycle: refactor

#218 :recycle: [re] userId 같이 넘겨주기 완료
  src/dtos/post.dto.js
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: :recycle: refactor

#220 ✨ feat: 자기소개 수정기능 추가, 최본게 & 스크립트 조회 스웨거 수정
  src/controllers/post.controller.js
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/index.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :sparkles: feature, :recycle: refactor

#223 [refactor]/accessToken 시간 연장
  src/services/auth.service.js
Labels: :recycle: refactor

#225 [refactor] 인기템플릿 file_pdf , file_ppt 속성추가
  src/controllers/template.controller.js
  src/dtos/template.dto.js
  src/repositories/template.repository.js
Labels: :recycle: refactor
