Repository BEMINE-UMC/Server, pull requests merged in 2025-01, with the labels that each got.

#17 좋아요 누르기 API 구현
  src/controllers/post.controller.js
  src/dtos/post.dto.js
  src/error.js
  src/errors/post.error.js
  src/index.js
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: :sparkles: feature

#20 [✨FEAT]연혁 불러오기 기능 추가
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/errors/user.error.js
  src/index.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :sparkles: feature

#23 Docs/#22 swagger 추가 차차
  src/controllers/post.controller.js
  src/controllers/template-view.controller.js
  src/controllers/template.controller.js
  src/dtos/template.dto.js
  src/errors/template.error.js
  src/index.js
  src/repositories/template.repository.js
  src/services/template.service.js
Labels: :memo: docs

#25 [📝DOCS] #21 Swagger 추가
  src/controllers/post.controller.js
  src/controllers/template.controller.js
  src/controllers/user.controller.js
  src/index.js
Labels: :memo: docs

#29 docs/#28-Swagger 추가
  src/controllers/post.controller.js
  src/index.js
Labels: :memo: docs

#34 [docs] 옌찌 담당 API 스웨거 작성
  src/controllers/post.controller.js
  src/controllers/template.controller.js
  src/index.js
Labels: :memo: docs

#36 docs/swagger-api-reorder
  src/index.js
Labels: :memo: docs

#38 [📝 docs] swagger 태그 수정
  src/controllers/post.controller.js
  src/controllers/template.controller.js
  src/controllers/user.controller.js
Labels: :memo: docs

#42 bug/Prisma DB URL 추가
  prisma/schema.prisma
Labels: :bug: bug

#43 bug: fix index endpoint
  src/index.js
Labels: :bug: bug

#46 [feat] 게시물 스크랩 누르기 API
  prisma/schema.prisma
  src/controllers/post.controller.js
  src/dtos/post.dto.js
  src/error.js
  src/errors/post.error.js
  src/index.js
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: :sparkles: feature

#49 docs/template.error.js 에러코드 변경(차차)
  src/errors/template.error.js
Labels: :memo: docs

#56 [Feat] 스크랩한 게시물 목록 조회
  src/controllers/post.controller.js
  src/dtos/post.dto.js
  src/errors/post.error.js
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: :sparkles: feature

#66 [feat] 템플릿 삭제 API 개발
  src/controllers/template.controller.js
  src/dtos/template.dto.js
  src/errors/template.error.js
  src/index.js
  src/repositories/template.repository.js
  src/services/template.service.js
Labels: :sparkles: feature

#64 [feat] 템플릿 단일 조회 API 개발
  src/controllers/template-view.controller.js
  src/controllers/template.controller.js
  src/dtos/template.dto.js
  src/errors/template.like.error.js
  src/index.js
  src/repositories/template.repository.js
  src/services/template.service.js
Labels: :sparkles: feature

#62 [Feat] 사용자 프로필 사진 수정
  middleware.js
  package-lock.json
  package.json
  src/controllers/user.controller.js
  src/dtos/user.dto.js
  src/errors/user.error.js
  src/index.js
  src/repositories/post.repository.js
  src/repositories/user.repository.js
  src/services/user.service.js
Labels: :sparkles: feature

#80 i - #16 #50 #54 #58
  prisma/schema.prisma
  src/controllers/post.controller.js
  src/controllers/user.controller.js
  src/dtos/post.dto.js
  src/dtos/user.dto.js
  src/index.js
Labels: :recycle: refactor

#87 Docs/#81-기존 API 스웨거 추가
  package-lock.json
  package.json
  src/controllers/auth.controller.js
  src/controllers/post.controller.js
Labels: :memo: docs

#91 Refactor/edit swagger api
  src/controllers/post.controller.js
  src/index.js
Labels: :recycle: refactor

#90 Refacto r: 옌찌 담당 API Swagger, 헤더 추가
  src/controllers/post.controller.js
  src/controllers/template.controller.js
  src/errors/post.error.js
  src/index.js
Labels: :recycle: refactor

#92 Refactor/#86-템플릿-파일-조회-API
  src/controllers/template.controller.js
  src/dtos/template.dto.js
  src/errors/template.error.js
  src/errors/template.like.error.js
  src/index.js
  src/repositories/template.repository.js
  src/services/template.service.js
Labels: :memo: docs, :recycle: refactor

#95 docs/#94-스웨거-수정-tags
  src/controllers/post.controller.js
  src/controllers/template.controller.js
Labels: :memo: docs

#101 Feature/#71 write post api
  middleware.js
  package-lock.json
  prisma/schema.prisma
  src/controllers/portfolio.post.controller.js
  src/controllers/post.controller.js
  src/dtos/template.dto.js
  src/errors/post.error.js
  src/index.js
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: :sparkles: feature, :recycle: refactor

#102 #99 게시글 상세조회 api
  src/controllers/post.controller.js
  src/dtos/post.dto.js
  src/repositories/post.repository.js
  src/services/template.service.js
Labels: :sparkles: feature

#103 [feat] 게시글 삭제 API
  src/controllers/post.controller.js
  src/errors/post.error.js
  src/index.js
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: :sparkles: feature, :recycle: refactor

#113 bug: 충돌 해결
  src/services/post.service.js
Labels: :bug: bug

#108 [bug] 수정/삭제 충돌 해결
  src/controllers/post.controller.js
  src/errors/post.error.js
  src/index.js
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: :bug: bug

#119 [bug] 게시글 삭제 충돌 해결
  src/controllers/post.controller.js
Labels: :bug: bug

#122 [refactor] 최근본 게시물 데이터 추가 기능
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: :recycle: refactor

#126 Feat/#123-이메일 인증(발송,검증) API
  package-lock.json
  package.json
  src/controllers/auth.controller.js
  src/dtos/auth.dto.js
  src/errors/auth.error.js
  src/index.js
  src/repositories/auth.repository.js
  src/services/auth.service.js
Labels: :sparkles: feature

#135 Feat: (로그인 전/후) 템플릿 목록 조회
  src/controllers/template.controller.js
  src/dtos/template.dto.js
  src/errors/template.error.js
  src/index.js
  src/repositories/template.repository.js
  src/services/template.service.js
Labels: :memo: docs, :sparkles: feature

#137 Feat: (로그인 전/후) 게시물 전체 조회 --v2
  src/controllers/post.controller.js
  src/dtos/post.dto.js
  src/dtos/template.dto.js
  src/errors/post.error.js
  src/index.js
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: :memo: docs, :sparkles: feature

#139 FEAT template, post 좋아요 스크랩 삭제 구현
  src/controllers/post.controller.js
  src/controllers/template.controller.js
  src/dtos/post.dto.js
  src/dtos/template.dto.js
  src/errors/template.error.js
  src/index.js
  src/repositories/post.repository.js
  src/repositories/template.repository.js
  src/services/template.service.js
Labels: :memo: docs, :sparkles: feature, :recycle: refactor

#141 [Feat] 템플릿 생성/수정 #138
  middleware.js
  prisma/schema.prisma
  src/controllers/template.controller.js
  src/dtos/template.dto.js
  src/errors/template.error.js
  src/index.js
  src/repositories/template.repository.js
  src/services/template.service.js
Labels: :memo: docs, :sparkles: feature, :recycle: refactor

#134 feat:#44-좋아요 누른 게시물 조회 api
  src/controllers/auth.controller.js
  src/controllers/post.controller.js
  src/dtos/post.dto.js
  src/index.js
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: :memo: docs, :sparkles: feature

#143 [bug] import 중복 및 swagger수정
  src/controllers/post.controller.js
  src/errors/template.error.js
  src/services/template.service.js
Labels: :bug: bug

#144 feat: 사용자 작성 게시물 조회 api
  src/controllers/post.controller.js
  src/repositories/post.repository.js
  src/services/post.service.js
Labels: :sparkles: feature

#148 [Refactor] 템플릿 관련 api 수정 및 sql문 수정
  src/controllers/post.controller.js
  src/controllers/template.controller.js
  src/dtos/template.dto.js
  src/errors/template.error.js
  src/index.js
  src/repositories/post.repository.js
  src/repositories/template.repository.js
  src/services/post.service.js
  src/services/template.service.js
Labels: :bug: bug, :memo: docs, :recycle: refactor

#149 feat:#132-비밀번호 재설정 api
  src/controllers/auth.controller.js
  src/dtos/auth.dto.js
  src/errors/auth.error.js
  src/index.js
  src/repositories/auth.repository.js
  src/services/auth.service.js
Labels: :sparkles: feature

#150 docs/#132-스웨거 코드 추가
  src/controllers/auth.controller.js
Labels: :memo: docs

#152 feat: 사용자 이메일 찾기 api 구현
  src/controllers/auth.controller.js
  src/controllers/user.controller.js
  src/dtos/auth.dto.js
  src/errors/auth.error.js
  src/errors/user.error.js
  src/index.js
  src/repositories/auth.repository.js
  src/repositories/user.repository.js
  src/services/auth.service.js
  src/services/user.service.js
Labels: :sparkles: feature, :recycle: refactor

#154 Refactor/다른 사용자 게시물 조회 api
  src/controllers/post.controller.js
Labels: :recycle: refactor
